// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/test": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/test";
  };
  "./App.tsx": {
    id: "App";
    page: "/";
  };
  "./test.tsx": {
    id: "test";
    page: "/test";
  };
};